branch-defaults:
  develop:
    environment: sysbot-dev
    group_suffix: null
  production:
    environment: sysbot-production
    group_suffix: null
environment-defaults:
  sysbot-test:
    branch: null
    repository: null
global:
  application_name: sysbot
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
